config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users
  resources :feeds do
    resources :comments
  end

  root 'static#home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :feed
end

app/models/concerns/visible.rb
module Visible
  extend ActiveSupport::Concern

  VALID_STATUSES = ['public', 'private', 'archived']

  included do
      validates :status, inclusion: { in: Visible::VALID_STATUSES }
  end

  def archived?
      status == 'archived'
  end
end

app/models/feed.rb
class Feed < ApplicationRecord
  include Visible
  belongs_to :user
  has_many :comments, dependent: :destroy

  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :feeds, dependent: :destroy
  has_many :comments, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_person_name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  def after_sign_in_path_for(resource)
    feeds_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @feed = Feed.find(params[:feed_id])
    @comment = Comment.new
  end

  def create
    comment_params = params.require(:comment).permit(:content, :user_id, :feed_id)

    user = User.find(comment_params[:user_id])
    feed = Feed.find(comment_params[:feed_id])

    @comment = Comment.new(content: comment_params[:content], user: user, feed: feed)

    if @comment.save
      redirect_to feed_path(feed)
    else
      render :new
    end
  end

  def destroy
    feed = Feed.find(params[:feed_id])
    @comment = feed.comments.find(params[:id])
    @comment.destroy

    redirect_to feed_path(feed), status: :see_other
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  def index
    @feeds = Feed.all
  end

  def show
    @feed = Feed.find(params[:id])
  end

  def new
    @feed = Feed.new
  end

  def create
    @user = User.find(current_user.id)
    @feed = @user.feeds.create(feed_params)

    if @feed.save
      redirect_to @feed
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @feed = Feed.find(params[:id])
  end

  def update
    @feed = Feed.find(params[:id])

    if @feed.update(feed_params)
      redirect_to @feed
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @feed = Feed.find(params[:id])
    @feed.destroy

    redirect_to @feed, status:  :see_other
  end

  private
    def feed_params
      params.require(:feed).permit(:body, :status)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.slim
.mb-2
  - if comment.user_id
    h6
      | >
      =<< User.find(comment.user_id).name
      span.text-muted
        |<< (
        = time_ago_in_words(comment.created_at)
        | )
    p
      |< >>
      =<> comment.content
      - if comment.user_id == current_user.id
        =<> link_to [comment.feed, comment], data: { turbo_method: :delete, turbo_confirm: "Gonna delete this message?" } do
          = fa_icon 'trash', class: "text-danger"

app/views/comments/_form.html.slim
= form_with model: [@feed, @feed.comments.build] do |form|
  = form.hidden_field :user_id, value: current_user.id
  = form.hidden_field :feed_id, value: @feed.id
  .input-group
    = form.text_field :content, placeholder: "Comment...", class: "form-control"
    = form.submit(class: "btn btn-primary")

app/views/feeds/_form.html.slim
= form_with model: @feed do |form|
  .mb-5
    = form.text_area :body, { class: "form-control", rows: "5" }
    - @feed.errors.full_messages_for(:body).each do |message|
      div
        = message

  .mb-2.d-flex.justify-content-between
    .d-flex.align-items-center
      .me-2
        = form.label :status, class: "form-label"
      div
        = form.select :status, Visible::VALID_STATUSES, { selected: feed.status || 'public' }, { class: "form-select" }
    div
      = form.submit(class: "btn btn-success px-3")

app/views/feeds/edit.html.slim
.container.w-50.mt-5
  - if user_signed_in?
    h2.h3.text-center.mb-3 Edit your feed
    .bg-light.border.rounded.p-3.mt-2
      = render "form", feed: @feed

  - else
    .alert.alert-info.m-3.w-50.mx-auto.text-center.fs-5
      p.m-0 You need to log in first to add new articles.

app/views/feeds/index.html.slim
.container.py-3
  h1.text-dark.text-center Welcome to Feeds!

  .row.mt-5.justify-content-center
    - @feeds.each do |feed|
      - unless feed.archived?
        .col-8.mb-2
          .card
            .card-body
              .d-flex.justify-content-between.mb-2
                div.mb-3
                  h4.card-title
                    =>> User.find(feed.user_id).name
                  span.text-muted
                    = time_ago_in_words(feed.created_at)
                div
                  - if feed.user_id == current_user.id
                    = link_to edit_feed_path(feed.id) do
                      = fa_icon 'edit', class: 'text-dark me-2'
                    = link_to feed_path(feed.id), data: { \
                      turbo_method: :delete,
                      turbo_confirm: "Are you sure?" } do
                      = fa_icon 'trash', class: 'text-danger'
              p.card-text.my-3= feed.body
              = link_to "Comment", feed, class: "btn btn-outline-success rounded-pill btn-sm mt-3"

app/views/feeds/new.html.slim
.container.w-50.mt-5
  - if user_signed_in?
    h2.h3.text-center.mb-3 Share your brilliant thoughts
    .bg-light.border.rounded.p-3.mt-2
      = render "form", feed: @feed

  - else
    .alert.alert-info.m-3.w-50.mx-auto.text-center.fs-5
      p.m-0 You need to log in first to add new articles.

app/views/feeds/show.html.slim
.container.p-3.w-50.rounded.bg-light.my-3
  .d-flex.justify-content-between.align-items-center
    div
      h1= User.find(@feed.user_id).name
      span.text-muted
        = time_ago_in_words(@feed.created_at)
    div
      - if user_signed_in?
        - if current_user.id == @feed.user_id
          .btn-group
            = link_to "Edit", edit_feed_path(@feed), class: "btn btn-light"
            = link_to "Destroy", feed_path(@feed), class: "btn btn-light text-danger", data: { \
              turbo_method: :delete,
              turbo_confirm: "Are you sure?" \
            }

  hr.border.border-danger.border-2.opacity-50
  div.my-5
    p.h5.lh-lg = @feed.body

  div
    = render "comments/form"

.container.p-3.w-50
  hr.border.border-danger.border-1.opacity-100
  h5 See what others are talking about
  hr.border.border-danger.border-1.opacity-100
  div
    - if @feed.comments
      = render @feed.comments

app/views/layouts/application.html.slim
doctype html
html
  head
    title FEEDS
    meta name="viewport" content="width=device-width,initial-scale=1" /
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_importmap_tags

  body
    = render partial: "shared/navbar"
    = yield

app/views/shared/_navbar.html.slim
nav.navbar.navbar-expand-lg.bg-body-tertiary
  .container
    = link_to "FEEDS", root_path, class: "navbar-brand"
    button.navbar-toggler type="button" data-bs-toggle="collapse" data-bs-target ="#navbarSupportedContent"
      span.navbar-toggler-icon
    .collapse.navbar-collapse#navbarSupportedContent
      ul.navbar-nav.me-auto.mb-2.mb-lg-0
        - if user_signed_in?
          li.nav-item
            = link_to "Feeds", feeds_path, class: "nav-link"
          li.nav-item
            = link_to "Add New", new_feed_path, class: "nav-link"
        - else
          li.nav-item
            a.nav-link href="#" About Us
          li.nav-item
            a.nav-link href="#" FAQ
      .d-flex
        - if user_signed_in?
          div
            = button_to user_path(current_user.id), method: :get, class: "btn btn-light" do
              = current_user.name
          div
            = button_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-danger"
        - else
          div
            = link_to "Create New Account", new_user_registration_path, class: "btn btn-primary me-2"
          div
            = link_to "Log in", new_user_session_path, class: "btn btn-outline-primary me-2"

app/views/users/show.html.slim
.container.p-3.w-50.rounded.bg-light.my-3
  h3 Profile
  hr.border.border-success.border-1.opacity-100
  .mb-2.fs-5
    |> User Name :
    = @user.name
  .mb-5.fs-5
    |> Email :
    = @user.email
  .mb-2.d-flex
    = button_to "Edit", edit_user_registration_path, method: :get, class: "btn btn-success me-2 px-4"